# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rhel75"
  config.vm.define "rpmbuild"
  config.vm.hostname = "rpmbuild"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = 4096
    v.vmx["numvcpus"] = 2
    v.gui = true
    v.vmx["ethernet0.pcislotnumber"] = "33"
  end
  config.registration.name = "rpmbuild"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/update.yml"
  end
end
