# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.define "tower" do |tower|
    config.vm.hostname = "tower.local"
    tower.vm.box = "ansible/tower"
    tower.vm.box_version = "3.5.0"
    tower.vm.network :private_network,ip: "192.168.56.2"
    tower.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 4096
      v.cpus = 2
    end
  end

  config.vm.define "server" do |server|
    config.vm.hostname = "server.local"
    server.vm.box = "generic/rhel7"
    server.vm.box_version = "1.9.18"
    server.vm.network :private_network,ip: "192.168.56.10"
    server.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/deploy-demo.yml"
      ansible.vault_password_file = "ansible/.vp"
      ansible.inventory_path = "ansible/inventory"
      ansible.become = true
    end
  end
end
