#!/bin/bash

HOSTNAME=`curl http://169.254.169.254/latest/dynamic/instance-identity/document | grep instanceId | awk {'print $3'} | sed s/\"//g | sed s/\,//g`; sed -i 's/^HOSTNAME=*.*$/HOSTNAME='\"$HOSTNAME.a2.vary.redhat.com\"'/' /etc/sysconfig/network
