Vagrant.configure(2) do |config|
  
  # What box?
  config.vm.box = "fedora/25-cloud-base" 

  config.vm.hostname = "vagranthost.mobile.mth" 

  # synced folder
  config.vm.synced_folder ".", "/lab", 
  create: true, 
  owner: "root",
  group: "root"

end
