pipeline {
    agent any

   stages {

        stage('Test') {
            steps {
                sh 'ansible --version'
                sh 'ansible-playbook --inventory-file tests/inventory --syntax-check tests/test.yml'
            }
        }

    }
}
